// <auto-generated />
using System;
using Gestao_de_Entregas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gestao_de_Entregas.Migrations
{
    [DbContext(typeof(CalculadorDbContext))]
    [Migration("20200220023130_calculador")]
    partial class calculador
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Gestao_de_Entregas.Data.BancoDeHoras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HorasExtras")
                        .HasColumnType("time(6)");

                    b.Property<string>("Justificativa")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("BancoDeHoras");
                });

            modelBuilder.Entity("Gestao_de_Entregas.Data.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Funcao")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<TimeSpan>("HoraAlmocoRetorno")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("HoraAlmocoSaida")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("HoraIncio")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("HoraTermino")
                        .HasColumnType("time(6)");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Registro")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("Gestao_de_Entregas.Data.HorasFuncionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("Entrada")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("Extras")
                        .HasColumnType("time(6)");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Saida")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("HorasFuncionarios");
                });

            modelBuilder.Entity("Gestao_de_Entregas.Data.BancoDeHoras", b =>
                {
                    b.HasOne("Gestao_de_Entregas.Data.Funcionario", null)
                        .WithMany("BancoDeHoras")
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gestao_de_Entregas.Data.HorasFuncionario", b =>
                {
                    b.HasOne("Gestao_de_Entregas.Data.Funcionario", null)
                        .WithMany("CartaoPonto")
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
